### PR TITLE
Add control spec helper

### PR DESCRIPTION
**Pull request by eshamow**
Fixed and rebased - @terrimonster you should probably double-check gem setup again to confirm I'm right, though.

### CODE REVIEW

**Comment by eshamow** [comment]
This replaces the badly botched #14 for which I just torched my rebase. No point in even TRYING to fix that.

**Comment by terrimonster** [comment]
Hrm. Seems to be an issue:

> bundle exec rake vplugins
> Vagrant experienced a version conflict with some installed plugins!
> This usually happens if you recently upgraded Vagrant. As part of the
> upgrade process, some existing plugins are no longer compatible with
> this version of Vagrant. The recommended way to fix this is to remove
> your existing plugins and reinstall them one-by-one. To remove all
> plugins:

```
rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems
```

Note if you have an alternate VAGRANT_HOME environmental variable
set, the folders above will be in that directory rather than your
user's home directory.

The error message is shown below:

Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    vagrant (= 1.7.4) ruby depends on
      bundler (<= 1.10.5, >= 1.5.2) ruby

  Current Bundler version:
    bundler (1.10.6)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (<= 1.10.5, >= 1.5.2) ruby', which is required by gem 'vagrant (= 1.7.4) ruby', in any of the sources.

**Comment by terrimonster** [comment]
Seems to be a lot of errors with the commit:

> bundle exec rake spec --trace
> *\* Invoke spec (first_time)
> *\* Execute spec
> *\* Invoke spec_prep (first_time)
> *\* Execute spec_prep
> Installing modules with r10k
> rake aborted!
> TypeError: can't convert nil into String
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/control_spec_helper-0.0.1/lib/control_spec_helper/control_spec_helper.rb:35:in `join'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/control_spec_helper-0.0.1/lib/control_spec_helper/control_spec_helper.rb:35:in`profile_path'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/control_spec_helper-0.0.1/lib/control_spec_helper/control_spec_helper.rb:104:in `profile_fixtures'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/control_spec_helper-0.0.1/lib/control_spec_helper/rake_tasks.rb:75:in`block in <top (required)>'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in`block in execute'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in`execute'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in`invoke'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/control_spec_helper-0.0.1/lib/control_spec_helper/rake_tasks.rb:80:in `block in <top (required)>'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in`call'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in`each'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in`block in invoke_with_call_chain'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in`invoke_with_call_chain'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in`invoke_task'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in`each'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in`run_with_threads'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in`block in run'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in`run'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/bin/rake:23:in`load'
> /Users/thabe3/.rbenv/versions/1.9.3-p551/bin/rake:23:in `<main>'
> Tasks: TOP => spec_prep

I'm so very sorry but I really can't accept the PR :(

**Comment by eshamow** [comment]
There's no need to apologize! It's a terrible, buggy PR.

I'll get on it.

**Pull request closed without merging**
