### PR TITLE
Updated PE version and CentOS 7 support

### PR DESCRIPTION
**Pull request by aharden**
Tested with Vagrant 1.7.4 & Virtualbox 5.0.10 on Mac OS 10.10.5 and Windows 7 SP1.

### CODE REVIEW

**Comment by terrimonster** [comment]
Please remove version 2015.2.3. I would prefer to add it when it is officially available and supported.

Also - the update to puppetlabs boxes. Any particular reason for this?

**Comment by aharden** [comment]
@terrimonster You're confusing PE 2015.2.3 (released Nov 5, 2015 per https://docs.puppetlabs.com/pe/2015.2/release_notes.html) with PE 2015.3, the new feature release coming next week.

I put detailed notes into two of the attached commits.  Regarding the change in boxes:
With the virtualbox provider, vagrant couldn't connect to the centos/7 box for initial provisioning.  Connection timeouts occurred after the machine had fully booted.  This occurred with Vagrant 1.7.4 and Virtualbox 5.0.10 on Mac OS X 10.10.5.

**Comment by terrimonster** [comment]
Sorry it took me awhile to get back to this. Do me a big favor - can you PR a branch other than production? This will help me resolve any rebasing that needs to happen. Thanks!

**Comment by aharden** [comment]
Your only other branch is feature_branch, which is older than your current production branch.  Feel free to grab my repo's production branch and test, or provide an up-to-date branch to merge to.  I hope I'm not missing anything.

**Comment by terrimonster** [comment]
You would create a new branch on your end (name it something like newpupver or somesuch), push it to your account repo, then create a new pull request to my production branch.

**Comment by aharden** [comment]
Done.

**Pull request closed without merging**
